import Layout from "@/src/components/Layout";
import Navbar from "@/src/components/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs With Redux</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col items-center text-lg">
          <h2>This is a Redux Toolkit Learning Project for Self.</h2>
          <div className="flex gap-10 mt-5">
            <div className="flex flex-col items-center">
              <h2>Without Middleware</h2>
              <img
                src={"./redux-flow.gif"}
                alt="redux-gif"
                className="w-[500px]"
              />
            </div>

            <div className="flex flex-col items-center">
              <h2>With Middleware</h2>
              <img
                src={"./redux-flow-with-thunk.gif"}
                alt="redux-gif"
                className="w-[500px]"
              />
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
